import localFont from "next/font/local";

import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import Loading from "./loading"
import {  Suspense } from 'react';
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
// @import ‘bootstrap/dist/css/bootstrap.min.css’;
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Suspense fallback={<Loading />}>
          {/* <h2>Preview</h2> */}
          <Navbar/>
          {children}
          <Footer/>
        </Suspense>
        
      </body>
    </html>
  );
}
